// apps/service-demos/event-bus/scenarios/trading/mfe-market-watch/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { MarketWatch } from './MarketWatch';
import type { MFEModule, MFEServiceContainer } from '@mfe-toolkit/core';

let root: ReactDOM.Root | null = null;

const module: MFEModule = {
  metadata: {
    name: 'mfe-market-watch',
    version: '1.0.0',
    requiredServices: ['eventBus', 'logger'],
    capabilities: ['real-time-updates', 'stock-monitoring']
  },

  mount: async (element: HTMLElement, container: MFEServiceContainer) => {
    const services = container.getAllServices();
    root = ReactDOM.createRoot(element);
    root.render(<MarketWatch services={services} />);
    
    if (services.logger) {
      services.logger.info('[mfe-market-watch] Mounted successfully');
    }
  },
  
  unmount: async (container: MFEServiceContainer) => {
    if (root) {
      root.unmount();
      root = null;
    }
    
    const services = container.getAllServices();
    if (services.logger) {
      services.logger.info('[mfe-market-watch] Unmounted successfully');
    }
  }
};

export default module;

// apps/service-demos/modal/mfe-modal-solidjs/src/main.tsx
import { render } from 'solid-js/web';
import type { MFEModule, MFEServiceContainer } from '@mfe-toolkit/core';
import { App } from './App';

let cleanup: (() => void) | null = null;

const module: MFEModule = {
  metadata: {
    name: 'mfe-notification-solidjs',
    version: '1.0.0',
    requiredServices: ['notification'],
    capabilities: ['notification-demo']
  },

  mount: async (element: HTMLElement, container: MFEServiceContainer) => {
    const services = container.getAllServices();
    cleanup = render(() => <App services={services} />, element);
    
    if (services.logger) {
      services.logger.info('[mfe-notification-solidjs] Mounted successfully');
    }
  },
  
  unmount: async (container: MFEServiceContainer) => {
    if (cleanup) {
      cleanup();
      cleanup = null;
    }
    
    const services = container.getAllServices();
    if (services.logger) {
      services.logger.info('[mfe-notification-solidjs] Unmounted successfully');
    }
  }
};

export default module;
